trigger:
  branches:
    include:
    - master
  tags:
    include:
    - refs/tags/v*

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'

pool:
  vmImage: $(imageName)

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: npm install

- bash: |
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    echo ">>> Started xvfb"
  displayName: Start xvfb
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))
- bash: |
    echo ">>> Publish"    
    yarn install && yarn deploy
  displayName: Publish
  

  env:
    DISPLAY: ':99.0'
    VSCE_PAT: $(VSCE_PAT)